const { app, dialog } = require('electron');
const fs = require('fs');
const path = require('path');
const { Logger } = require('./logger');

const logger = new Logger('EnvManager');

// Environment variable management
class EnvManager {
  constructor() {
    this.isDev = process.env.NODE_ENV === 'development';
    this.envFile = this.isDev
      ? path.join(__dirname, '..', 'backend', '.env')
      : path.join(app.getPath('userData'), '.env');

    this.requiredVars = ['GOOGLE_API_KEY', 'FIREBASE_CONFIG'];
    this.env = {};
  }

  // Load environment variables from .env file
  load() {
    logger.info('Loading environment variables...');

    try {
      if (fs.existsSync(this.envFile)) {
        const content = fs.readFileSync(this.envFile, 'utf8');

        // Parse .env file
        content.split('\n').forEach(line => {
          line = line.trim();
          if (line && !line.startsWith('#')) {
            const [key, ...values] = line.split('=');
            const value = values.join('=').trim();

            // Remove quotes if present
            const cleanValue = value.replace(/^["']|["']$/g, '');
            this.env[key.trim()] = cleanValue;
          }
        });

        logger.info(`Loaded ${Object.keys(this.env).length} environment variables`);
        return true;
      } else {
        logger.warn(`.env file not found at ${this.envFile}`);
        return false;
      }
    } catch (error) {
      logger.error('Failed to load .env file', error);
      return false;
    }
  }

  // Validate required environment variables
  validate() {
    logger.info('Validating required environment variables...');

    const missing = this.requiredVars.filter(key => !this.env[key]);

    if (missing.length > 0) {
      logger.error('Missing required environment variables', { missing });
      return { valid: false, missing };
    }

    logger.info('All required environment variables present');
    return { valid: true, missing: [] };
  }

  // Get environment variable
  get(key) {
    return this.env[key] || process.env[key];
  }

  // Set environment variable (runtime only, doesn't persist)
  set(key, value) {
    this.env[key] = value;
    process.env[key] = value;
  }

  // Get all environment variables for backend
  getBackendEnv() {
    return {
      ...process.env,
      ...this.env,
      PORT: process.env.PORT || '5000',
      FLASK_ENV: this.isDev ? 'development' : 'production',
      PYTHONUNBUFFERED: '1'
    };
  }

  // Show dialog for missing variables
  async promptForMissing(mainWindow, missing) {
    const response = await dialog.showMessageBox(mainWindow, {
      type: 'warning',
      title: 'Configuration Required',
      message: 'Missing required configuration',
      detail: `The following environment variables are not configured:\n\n${missing.join('\n')}\n\nPlease configure them in Settings before using AI features.`,
      buttons: ['Open Settings', 'Continue Anyway'],
      defaultId: 0,
      cancelId: 1
    });

    return response.response === 0; // true if "Open Settings" clicked
  }

  // Create .env file from template
  createFromTemplate() {
    const templatePath = path.join(__dirname, '..', 'backend', '.env.example');

    if (fs.existsSync(templatePath)) {
      try {
        fs.copyFileSync(templatePath, this.envFile);
        logger.info(`Created .env file from template at ${this.envFile}`);
        return true;
      } catch (error) {
        logger.error('Failed to create .env from template', error);
        return false;
      }
    } else {
      // Create minimal .env
      const minimal = `# Lit-Rift Configuration
# Generated by Lit-Rift Desktop

# Google Gemini AI API Key
GOOGLE_API_KEY=your_api_key_here

# Firebase Configuration (JSON string)
FIREBASE_CONFIG={}
`;
      try {
        fs.writeFileSync(this.envFile, minimal);
        logger.info(`Created minimal .env file at ${this.envFile}`);
        return true;
      } catch (error) {
        logger.error('Failed to create minimal .env', error);
        return false;
      }
    }
  }

  // Get .env file path for user reference
  getEnvPath() {
    return this.envFile;
  }
}

module.exports = { EnvManager };
